export const LOAD_ISSUES_ERROR = "LOAD_ISSUES_ERROR";
export const LOAD_ISSUES_SUCCESS = "LOAD_ISSUES_SUCCESS";
export const LOAD_ISSUES_REQUEST = "LOAD_ISSUES_REQUEST";

export const LOAD_ISSUE_REQUEST = "LOAD_ISSUE_REQUEST";
export const LOAD_ISSUE_SUCCESS = "LOAD_ISSUE_SUCCESS";
export const LOAD_ISSUE_ERROR = "LOAD_ISSUE_ERROR"
export const LOAD_COMMENTS_SUCCESS = "LOAD_COMMENTS_SUCCESS";
export const LOAD_COMMENTS_ERROR = "LOAD_COMMENTS_ERROR";

export const LOAD_REPOSITORIES_REQUEST = "LOAD_REPOSITORIES_REQUEST";
export const LOAD_REPOSITORIES_SUCCESS = "LOAD_REPOSITORIES_SUCCESS";
export const LOAD_REPOSITORIES_ERROR = "LOAD_REPOSITORIES_ERROR";

export const USER_HAS_NOT_REPOSITORIES = "USER_HAS_NOT_REPOSITORIES";
