export const LOAD_ISSUES_ERROR = "LOAD_ISSUES_ERROR";
export const LOAD_ISSUES_SUCCESS = "LOAD_ISSUES_SUCCESS";
export const LOAD_ISSUES_REQUEST = "LOAD_ISSUES_REQUEST";

export const LOAD_ISSUE_SUCCESS = "LOAD_ISSUE_SUCCESS";
export const LOAD_COMMENTS_SUCCESS = "LOAD_COMMENTS_SUCCESS";
